let tagLongitude = "longitude"
let tagLatitude = "latitude"
let tagTitle = "title"
let tagDescription = "description"
let tagColor = "color"
let tagRotation = "rotation"

let tagMapType = "mapType"
let tagFlatMarkers = "flatMarkers"
let tagLonglatStyle = "longLatStyle"
